### PR TITLE
add API Connections() which returns list of connections found in conn…

### PR DESCRIPTION
**Pull request by mallochine**
…track

### CODE REVIEW

**Comment by alicebob** [comment]
thanks again! Just curious, what are you working on?

**Comment by mallochine** [comment]
I'm working on a module at Nutanix for our AHV (derivative of KVM) hypervisor. We found a bug in ulogd that didn't track ICMP quite accurately so we needed a replacement for ulogd. AFAIK, it seems like this was the only Go library to talk to conntrack for stats (are there any others?).

The network stats are collected from the hypervisor and shipped over to "Prism Central" (PC) which is a VM we run on the cluster. We have a homegrown service running on PC which does flow processing.

**Comment by alicebob** [comment]
fun, thanks!
(I couldn't find any other library back then when I wrote this.)

**Comment by mallochine** [comment]
so what did you write this module for?

**Comment by alicebob** [comment]
We were doing traffic analysis (packet sniffing). This was an experiment to see if this was faster than the pcap way. I don't think we ever used this module into production, though.

**Comment by mallochine** [comment]
was it faster than pcap?

**Comment by alicebob** [comment]
If I remember correctly, it was (but not that much), but using conntrack needs some setup, so we went with pcap after all. Pcap just works, no configuration needed.

**Pull request merged**
